
name: semantic-version

on:
  push:
    branches:
      - develop

jobs:
  release:
    runs-on: [self-hosted, build]

    permissions:
      contents: write
      issues: write
      pull-requests: write

    container:
      image: cerdo.unraveldata.com:50001/unravel-build/workflow-base-image:1.0
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}

    steps:
      - name: Cleanup old state
        run: rm -rf ${{ github.workspace }}/*

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          fetch-depth: 0
          fetch-tags: true
          ref: develop

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        
      - name: Set up Git identity
        run: |
          git config --global user.name "Unravel Builder"
          git config --global user.email "unravel-builder@unraveldata.com"

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

